### ISSUE TITLE
ya moruq bu ne

### ISSUE THREAD

**Issue by Teals53** [MrCoderN/krunker.io-hack-cheat-mod#11]
sitende bu kadar menü ve özellik varda niye scriptin kendisinde yok bunlar xD

misal
Player ESP (Wall Hack)
ESP Line Color
ESP Text Color
No Fire Limit
Speed Hack
Firebot
Auto Reload
Auto Aim
Auto Aim Range
No Recoil
No Reload
Fast Healer
Player Tracers
Auto Respawn
Show FPS
BunnyHop
Zoom range for Weapons
Scope range for Weapons
Aim Through Walls
Custom Aim Settings
Auto Weapon Swap

ve şu fotolar
![image](https://user-images.githubusercontent.com/13446881/55795997-a4bc9d80-5ad1-11e9-8381-15646a4145d0.png)
![image](https://user-images.githubusercontent.com/13446881/55796008-ad14d880-5ad1-11e9-92c6-5c8fe6a323da.png)

**Comment by Teals53** [comment]
sadece ultra reklam amaçlımı xD

**Comment by Teals53** [comment]
clickbait etc

**Comment by MrCoderN** [comment]
mod versiyonları her geçen gün değişiyor, sebebi krunker.io hileleri engelliyor

**Comment by Teals53** [comment]
hü
