### ISSUE TITLE
please fix

### ISSUE THREAD

**Issue by Cuciez** [MrCoderN/krunker.io-hack-cheat-mod#17]
so the new updated version you released about like 1 or 2 days ago kinda worked so now since I got that one I can get in krunker with like all the links and everything in it but when I get into an actual game nothing works please fix this.

**Comment by omercnet** [comment]
It’s an SEO scam, just wanting your clicks

**Comment by Cuciez** [comment]
I don't know what that means but I know that this script wasn't a scam it worked before but now it doesn't.

**Comment by MrCoderN** [comment]
This script is not scam and working. Thanks for using.
