### ISSUE TITLE
Nothng is working

### ISSUE THREAD

**Issue by Dragonswords101** [MrCoderN/krunker.io-hack-cheat-mod#18]
Broken again :(

**Comment by Cuciez** [comment]
sadly yes it is

**Comment by MrCoderN** [comment]
try again it's working for me

**Comment by Dragonswords101** [comment]
Its working now

**Comment by Dragonswords101** [comment]
Dissconection error happens now :(

**Comment by Cuciez** [comment]
either we are doing something wrong or you just need to change something

**Comment by MrCoderN** [comment]
FIXED* Please try again thank you :)
