### ISSUE TITLE
Anti Cheat in the new update may 1st 2019 version 1.2.3

### ISSUE THREAD

**Issue by bduiwaligo** [MrCoderN/krunker.io-hack-cheat-mod#19]
![Screenshot 2019-05-01 at 10 38 27 AM](https://user-images.githubusercontent.com/49958306/57025671-76783c80-6bfd-11e9-95bf-219ef5accc97.png)

**Comment by D1str1ctNINE** [comment]
i am with same problem.

**Comment by oscar12321** [comment]
me too

**Comment by T-Ghoul** [comment]
me too

**Comment by sabrt00th** [comment]
Mhm. Same issue.

**Comment by acer130** [comment]
i have the same problem as well but i am currently trying to fix, and if I can't, I will download MrCoderN's again and learn how. (in the code he wrote an aimbot and other hack patches)

**Comment by bduiwaligo** [comment]
@acer130 tell me when u think you got it working please thanks

**Comment by MrCoderN** [comment]
FIXED* Please try again thank you :)
