### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by NintendoKid139** [MrCoderN/krunker.io-hack-cheat-mod#21]
i was loading in and the screen went white and said "sorry krunker crashed." please fix this

**Comment by T-Ghoul** [comment]
me too

**Comment by Aryan1701** [comment]
Same Here

**Comment by MrCoderN** [comment]
FIXED* Please try again thank you :)

**Comment by NintendoKid139** [comment]
> FIXED* Please try again thank you :)

it crashed again and can't load
