### ISSUE TITLE
Krunker will not load anymore, due to its latest patch update.

### ISSUE THREAD

**Issue by BoxBee39** [MrCoderN/krunker.io-hack-cheat-mod#22]
Krunker will not load anymore, due to its latest patch update. Please Fix Soon

**Comment by Cuciez** [comment]
yes that happens to me to

**Comment by Cuciez** [comment]
![Screenshot 2019-05-02 at 8 22 05 AM](https://user-images.githubusercontent.com/49407593/57086717-7cc8f000-6cb3-11e9-97df-6e7bebf13a02.png)

**Comment by MrCoderN** [comment]
FIXED* Please try again thank you :)
