### ISSUE TITLE
Please remove the "krunkerio.net" and other texts, they're really annoying.

### ISSUE THREAD

**Issue by richardletshacks** [MrCoderN/krunker.io-hack-cheat-mod#24]

**Comment by omercnet** [comment]
try this adware free version.. https://github.com/omercnet/KrunkBot

**Comment by MrCoderN** [comment]
They need to be there because of recognizing

**Comment by omercnet** [comment]
@richardletshacks try this instead https://github.com/omercnet/KrunkBot no ads
