### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ItsDonD** [MrCoderN/krunker.io-hack-cheat-mod#26]
Hi, I Was downloading a Kruker Hack And its Crashing Whenever I log in. Please help

**Comment by T-Ghoul** [comment]
![Screenshot 2019-05-09 at 8 15 17 PM](https://user-images.githubusercontent.com/50172965/57452779-3cf79f00-7297-11e9-9cff-57bdd3cd640a.png)
crash for me too

**Comment by ShadowRocks2** [comment]
Same For me too!
![Krunker io broken](https://user-images.githubusercontent.com/44444243/57453645-ebb6c380-7234-11e9-918c-7021af55f542.png)

**Comment by jpep0405** [comment]
Me too!

**Comment by bduiwaligo** [comment]
Yep
![Screenshot 2019-05-09 at 8 47 42 AM](https://user-images.githubusercontent.com/49958306/57458694-6680de00-7237-11e9-8554-41e8cd6c0866.png)

**Comment by MrCoderN** [comment]
It's working again
