### ISSUE TITLE
Patched

### ISSUE THREAD

**Issue by fahrennheit** [MrCoderN/krunker.io-hack-cheat-mod#31]
The game is patched today, probably new antivirus update as of may 10th.

**Comment by MrCoderN** [comment]
its working for me

**Comment by omercnet** [comment]
> The game is patched today, probably new antivirus update as of may 10th.

try this instead https://github.com/omercnet/KrunkBot works well without ads

**Comment by MrCoderN** [comment]
fixed

**Comment by MeTeC-FR** [comment]
Hello Fahrennheit, could you please update your ZombsRoyale script ? I can't make it work, there is an error in your last manifest, Trailing comma not allowed.

Could you look at it ? Thanks !
