### ISSUE TITLE
Not working as of the new update 1.2.5

### ISSUE THREAD

**Issue by bduiwaligo** [MrCoderN/krunker.io-hack-cheat-mod#33]
![Screenshot 2019-05-16 at 2 45 29 PM](https://user-images.githubusercontent.com/49958306/57882467-678eae00-77e9-11e9-9ed8-29c36db90c3a.png)

**Comment by giehh** [comment]
SAME!!!!!

**Comment by giehh** [comment]
![Screenshot 2019-05-16 at 3 27 48 PM](https://user-images.githubusercontent.com/49963486/57884825-33b68700-77ef-11e9-801c-00b3f754f8eb.png)

**Comment by giehh** [comment]
PLEASE FIX THIS

**Comment by Al67945** [comment]
SAME! THE NEW UPDATE MAKES THIS UNUSABLE!!!!
PLEASEEEE FIX/Update

**Comment by bduiwaligo** [comment]
When will you fix the script

**Comment by MrCoderN** [comment]
I fixed aimbot crash, however I do not share because new krunker.io anti cheat auto disconnect you from game

**Comment by bduiwaligo** [comment]
ok

**Comment by MrCoderN** [comment]
fixed
