### ISSUE TITLE
button not working right

### ISSUE THREAD

**Issue by themandudechild** [MrCoderN/krunker.io-hack-cheat-mod#35]
I did pressed the blue font button that says krunker.io hacks. All it showed was just the players. How do you fix this?

**Comment by GtaMasterYT** [comment]
same. I think the script is broken currently.

**Comment by themandudechild** [comment]
also, when you turn on fire bot and heal faster, when you click the tab for the hacks it disappears

**Comment by MrCoderN** [comment]
fixed
