### ISSUE TITLE
Fire Bot and Fast healer not working

### ISSUE THREAD

**Issue by jonyisme** [MrCoderN/krunker.io-hack-cheat-mod#41]
When i try using the fire bot and healer it dose not work. It shows no sign of being activated or working. Everytime I die it gets automatically turned off and i have to turn it back on but it dosen't work.

**Comment by devarosw** [comment]
When i try using the fire bot and healer it dose not work. It shows no sign of being activated or working. Everytime I die it gets automatically turned off and i have to turn it back on but it dosen't work.

**Comment by MrCoderN** [comment]
fixed try again
