### ISSUE TITLE
SCRIPT DETECTED

### ISSUE THREAD

**Issue by NaturesProphet** [MrCoderN/krunker.io-hack-cheat-mod#46]
the game now says SCRIPT DETECTED

**Comment by sadykhzadeh** [comment]
![image](https://user-images.githubusercontent.com/51178055/58593661-8f1b5700-827c-11e9-94d4-f5fb66b19c6c.png)

**Comment by T-Ghoul** [comment]
that happens for me too

**Comment by NaturesProphet** [comment]
and also, the automatic reload and infinite ammo is not working too

**Comment by NintendoKid139** [comment]
same here.

**Comment by MenmaChan12** [comment]
Same here.

**Comment by ChinchyApollo81** [comment]
Bro, this game has an anti cheat or what??

**Comment by MrCoderN** [comment]
fixed watch video
