### ISSUE TITLE
Krunker.io is not working

### ISSUE THREAD

**Issue by Punisher2919** [MrCoderN/krunker.io-hack-cheat-mod#47]
when I play after 5 seconds it goes to a black screen

**Comment by T-Ghoul** [comment]
![Screenshot 2019-05-30 at 4 10 37 PM](https://user-images.githubusercontent.com/50172965/58618688-d42f9f80-82f5-11e9-8685-18344cb3f91b.png)
this is what happen after that 5 secounds

**Comment by MrCoderN** [comment]
fixed watch video
