### ISSUE TITLE
SCRIPT DETECTED

### ISSUE THREAD

**Issue by MasterGopnikLT** [MrCoderN/krunker.io-hack-cheat-mod#50]
It just says SCRIPT DETECTED and nothing is working - just black screen and says SCRIPT DETECTED

**Comment by sadykhzadeh** [comment]
When I create new tabs again and again (like in your video to fix), it shows the same:(

**Comment by hi2468789** [comment]
same here

**Comment by strumf007** [comment]
Same

**Comment by MasterGopnikLT** [comment]
lol. its same

2019-06-15, št, 18:33 strumf007 <notifications@github.com> rašė:

**Comment by MrCoderN** [comment]
fixed
