### ISSUE TITLE
Ammo, Heal, and speed hacks dont work

### ISSUE THREAD

**Issue by SpammedTony** [MrCoderN/krunker.io-hack-cheat-mod#51]
Were these just removed? Or are they being worked on? There is no button to enable them.

**Comment by ZeWhiteHatHacker** [comment]
There actually were none of them included in the script.

They are now in the New Update!
**### https://cutit.org/hax**

**Comment by 9in6is69** [comment]
is there keybinds because nothing in this works but it loads to krunker

**Comment by MrCoderN** [comment]
fixed
