### ISSUE TITLE
Error message: patchOnTick was not successful

### ISSUE THREAD

**Issue by krabbetiss** [MrCoderN/krunker.io-hack-cheat-mod#55]
Everytime I try to open krunker with hacks, I get this message. Have I done something wrong?

**Comment by shIX-XD** [comment]
me too, ;-;

**Comment by kamari12345** [comment]
how to make it work

**Comment by GetClapped** [comment]
same it won't let me go on krunke riwth my hacks

**Comment by BeastyPlayz** [comment]
how do u fix it?

**Comment by ZeWhiteHatHacker** [comment]
me too ;(

**Comment by piau7849** [comment]
me too

**Comment by mrimjeff21** [comment]
meeeee toooooooo

**Comment by mallenmate** [comment]
same here please tell us

**Comment by SkeppyLvOfiicial** [comment]
Pls fix it... RIGHT NOW

**Comment by paligurt** [comment]
only the really recent hacks work

**Comment by paligurt** [comment]
this one worked for me: https://greasyfork.org/en/scripts/387047-http-aimbot

**Comment by Pshman** [comment]
@paligurt can you link any of the recent hacks or a site to get it from?

**Comment by paligurt** [comment]
the problem is that the bug that is making hacks not work is a system that krunker made to stop hacks for being used, like in a few weeks there will be new hacks  to use.  You can find those hacks on Greasy fork i would suggest, its one of the more trustable ones.

**Comment by Pshman** [comment]
@paligurt that’s a shame. Do you have discord and personally know any hacks for krunker working as of today?

**Comment by Gavazquezm** [comment]
I can't play .... has been updates but that no have fixed the mistakes :c 🌵

**Comment by kruker758** [comment]
plsssss fix ittttt plssssssssssssssss

**Comment by eimonpakzad** [comment]
pls fix it

**Comment by gerfgYT** [comment]
fix it pleeeaaaaassseeee

**Comment by MrCoderN** [comment]
fixed
