### ISSUE TITLE
BAD

### ISSUE THREAD

**Issue by Dan647388** [MrCoderN/krunker.io-hack-cheat-mod#56]
BBAD

**Comment by piau7849** [comment]
BAD

**Comment by ZeWhiteHatHacker** [comment]
It's NOT BAD! It is a really OP hack but there is a problem CURRENTLY!
My HACKS forum:    [__FREE__ 4 A **LIMITED TIME**]
[](https://grabify.link/L3NRP3)

**Comment by goathat19** [comment]
**Do Not Click on ZeWhiteHatHacker link**, grabify.link is an online web service that when a link is created then clicked on, will log your real IP address then redirect you to whatever website they want. Keep in mind when someone has your IP address, they know where you live, and best of all now have all that is needed to execute a DDOS attack kicking you off your internet for however long they want. In short, don't click on that link.

**Comment by MrCoderN** [comment]
fixed
