### ISSUE TITLE
Ur links blocked by Google (goo.gl links)

### ISSUE THREAD

**Issue by ZeWhiteHatHacker** [MrCoderN/krunker.io-hack-cheat-mod#57]
_All_ of your goo.gl links have been **banned** by **Google**.
![slithere com goo gl link blocked](https://user-images.githubusercontent.com/51604173/61176058-670a6c00-a60e-11e9-8423-c34192b3fd86.PNG)

**Comment by MrCoderN** [comment]
fixed - you can play again
