### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Emanuel500** [MrCoderN/krunker.io-hack-cheat-mod#60]
I installed the mod and tampermonker
<img width="1440" alt="Screen Shot 2019-08-07 at 7 03 32 PM" src="https://user-images.githubusercontent.com/53881973/62663581-199bc900-b946-11e9-9e81-f81a582a92fc.png">
<img width="1440" alt="Screen Shot 2019-08-07 at 7 03 43 PM" src="https://user-images.githubusercontent.com/53881973/62663589-202a4080-b946-11e9-8464-035c8a2e142e.png">

, open krunker.io activate mod, read page and it doesn't work

**Comment by NaNraptor** [comment]
For more technical error message than "It No WoRk fIX Pl3z I n3eD ThEm H4axorZ":

[bigdickjesusland] Patching the game script...
userscript.html?id=eba0af3d-3b28-4e27-ba8f-580423c70f83:753 Uncaught (in promise) Error: [bigdickjesusland] patchAnticheat was not successful
    at Logger.crash (userscript.html?id=eba0af3d-3b28-4e27-ba8f-580423c70f83:753)
    at applyPatch (userscript.html?id=eba0af3d-3b28-4e27-ba8f-580423c70f83:761)
    at patchAnticheat (userscript.html?id=eba0af3d-3b28-4e27-ba8f-580423c70f83:857)
    at patchGameScript (userscript.html?id=eba0af3d-3b28-4e27-ba8f-580423c70f83:885)
    at eval (userscript.html?id=eba0af3d-3b28-4e27-ba8f-580423c70f83:923)

**Comment by NaNraptor** [comment]
I looked into the code and it seems that ```const ft=eval``` is now ```const dt=eval"

I corrected it here: https://github.com/MrCoderN/krunker.io-hack-cheat-mod/blob/7de383c169dd0ad19de7ff0d7ccb910e414213c3/krunkerhack.user.js#L846 and here: https://github.com/MrCoderN/krunker.io-hack-cheat-mod/blob/7de383c169dd0ad19de7ff0d7ccb910e414213c3/krunkerhack.user.js#L847

After correcting those I got to this check: https://github.com/MrCoderN/krunker.io-hack-cheat-mod/blob/7de383c169dd0ad19de7ff0d7ccb910e414213c3/krunkerhack.user.js#L850

And the alert said: "POST THIS IN DISCORD document.querySelector("script[src*='js/game']")?'load':'loadgg'"

Finally I adjusted this line to bypass that check since Im not too sure what it does or why...

I am able to connect but get kicked within 1min with the message: "Disconnected If you have any extensions disable them."

**Comment by NaNraptor** [comment]
Also note that there is no Discord link in the Readme.md, that should be corrected too

**Comment by MrCoderN** [comment]
fixed for 8 august
