### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by TheDudeOnGitHub** [MrCoderN/krunker.io-hack-cheat-mod#61]
Whenever I enable this script, this happens.
![2019-08-08 (1)](https://user-images.githubusercontent.com/50783747/62741260-245e6880-b9ef-11e9-91f2-f60724a6cb91.png)
![2019-08-08 (4)](https://user-images.githubusercontent.com/50783747/62741264-288a8600-b9ef-11e9-9488-2d69d49cb5e7.png)

But whenever I disable the script and refresh, everything is normal.
![2019-08-08 (3)](https://user-images.githubusercontent.com/50783747/62741406-9b93fc80-b9ef-11e9-8b15-a4bf3a1ad21f.jpg)

Any help on this is appreciated.

**Comment by TheDudeOnGitHub** [comment]
meow

**Comment by JimmyJones430** [comment]
same with me

**Comment by MrCoderN** [comment]
fixed - you can play again
