### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by JimmyJones430** [MrCoderN/krunker.io-hack-cheat-mod#62]
Black Screen
![Screenshot 2019-08-10 at 15 20 52](https://user-images.githubusercontent.com/53697780/62821757-b2b72380-bb82-11e9-95bc-17816644c32b.png)
![Screenshot 2019-08-10 at 15 21 20](https://user-images.githubusercontent.com/53697780/62821759-b5b21400-bb82-11e9-8550-8c2871eaf831.png)

**Comment by JimmyJones430** [comment]
When i turn it off is work but when i turn it on and reload the page it doesnt work

**Comment by TheDudeOnGitHub** [comment]
meow

**Comment by MrCoderN** [comment]
fixed - you can play again
