### ISSUE TITLE
It says "loading" on the black screen and I can't go in

### ISSUE THREAD

**Issue by JacobHe1018** [MrCoderN/krunker.io-hack-cheat-mod#78]
When I press the screen, another tab comes up saying Short Url-blocked. It's only been working for 1 day

**Comment by Narek1202** [comment]
It says "loading" on the black screen and I can't go in

**Comment by JacobHe1018** [comment]
This keeps happening to me when I use the august hack

**Comment by MrCoderN** [comment]
fixed - you can play again

**Comment by JacobHe1018** [comment]
I can see the enemies but it doesn't auto aim

**Comment by JacobHe1018** [comment]
hey mr coder, The update now allows me to go into krunker but it seems like
the hack changed. It is very laggy and the aimbot doesn't seem to work even
if I click in the auto aim box

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
